module.exports = [
  {
    name: 'Marinellas Italian Restaurant',
    cuisine: 'Italian',
    neighborhood: 'Bickford Park',
    price: '$$$',
    vegetarian: false,
    byob: false,
    iterator: 1,
  }, 
  {
    name: 'Sansotei',
    cuisine: 'Japanese',
    neighborhood: 'Downtown Core',
    price: '$$$$',
    vegetarian: true,
    byob: false,
    iterator: 2,
  },
  {
    name: 'Lamesa Filipino Kitchen',
    cuisine: 'Filipino',
    neighborhood: 'Niagara',
    price: '$$',
    vegetarian: false,
    byob: true,
    iterator: 3,
  },
  {
    name: 'La Bella Managua',
    cuisine: 'Latin',
    neighborhood: 'Christie Pits',
    price: '$$$',
    vegetarian: false,
    byob: false,
    iterator: 4,
  },
  {
    name: 'Thoroughbred Food & Drink',
    cuisine: 'American',
    neighborhood: 'Entertainment District',
    price: '$',
    vegetarian: false,
    byob: false,
    iterator: 5,
  }
];